### ISSUE TITLE
Warn / inform users when they are picking inaccessible contrasts

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#122]
- https://github.com/mherchel/contrast-grid
- https://contrastgrid.com
- https://metageeky.github.io/contrast_table_analyzer/contrast-table.html

The above provide contrast grids, which we could point to or embed? 

Not sure if this is the best approach

**Comment by finnlewis** [comment]
@willguv @markconroy discuss this further?

**Comment by willguv** [comment]
@msayoung let's link to best guidance in sprint 11/12

**Comment by markconroy** [comment]
This will be very tricky since all our colour fields are optional. So the CMS will not know what are the colours set in your theme vs which ones are set in the CMS.

If you have someone who creates a base theme and sets the header background colour to white, then in the CMS sets header font colours to black, we'll report a contrast of 0, since our default heading background is black. We might get away with this if there is no sub-theme created by councils, but the chances of that happening are very low.

**Comment by msayoung** [comment]
Can we add something like this I wonder: https://khan.github.io/tota11y/ 

There is a Drupal module that only does editorial checks https://www.drupal.org/project/editoria11y

**Comment by markconroy** [comment]
@msayoung Does that work with colour contrast issues? And even if so, how is it going to know what colour variables are set in a subtheme? And even if it does, how will it now what variables are set in a subtheme from an admin theme page?

**Comment by willguv** [comment]
I think we should link to guidance, not try anything clever at this stage

**Comment by msayoung** [comment]
@willguv - @markconroy and I made something cool :) 
But we will also link to guidance

**Comment by markconroy** [comment]
Here's a short video of it working: https://youtu.be/7QXdROSw_44

**Comment by msayoung** [comment]
@willguv do you think this is now covered with our localgov_sa11y module?

**Comment by msayoung** [comment]
I think we should call this done for now, and if we want to add something else later we can do so
