### ISSUE TITLE
All content is publically available on the controller site

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#276]
All content created on any microsite is available on the controller without needing to login. You can see this by doing a site install,  creating a new site and then going to /node/2 path on the controller site as an anonymous user; E.g. https://demo.microsites.localgovdrupal.org/node/2. This is content that should only appear on the new site.

At a minimum this is an SEO issue (duplicate content on multiple sites), but it's not desirable to have content unexpectedly appearing on other sites.

With the addition of Pathauto (#271), this will create aliases which will also be accessible on the controller site. We could somehow prevent the creation of aliases on the controller site, but this doesn't prevent access to the content on the node ID path.

I can see 2 solutions to this:

1. We check which site a piece of content belongs to and return a 404 if the content doesn't belong to the site.
2. We don't allow unauthenticated users to access content on the controller site.

Option 2 is the simpler solution. The options are not mutually exclusive; we could do both.

@ekes @finnlewis @markconroy @msayoung Any thoughts on how serious this issue is and the potential solutions?

**Comment by msayoung** [comment]
Good spot @stephen-cox 

Am I mistaken but didnt we discuss / solve this in a previous sprint. 

I think it's not ideal that a piece of content appears on the controller site domain, so if we could implement one or both of the solutions it would be good. 

On option 1. would this also apply when you are logged in as a controller as well?

**Comment by markconroy** [comment]
I like option 2 - anonymous users can't access content on the controller site.

**Comment by stephen-cox** [comment]
Having thought about this a little more I think it's worth doing both. I know we're not (currently) supporting the installation of this into a current site, but if someone was to install the localgov_microsites_group module they can in theory start creating microsites, this make me think that we should be blocking access to microsite content on the controller site. There is also no need to have unauthenticated access to the control site when using the install profile, so I suggest we install and configure something like the [Require Login](https://www.drupal.org/project/require_login) module in the profile.

**Comment by ekes** [comment]
I can see use cases where you want to administer the content in one place the control site;
or at least have oversight of the content on all the microsites for quality/spam/whatever control.
I'd guess both use cases would want updating the admin/content pages somewhat. Maybe we'd want to do that no matter if the content from microsites is visible or not.
All this would be require a dedicated control site, and for that require login or similar seems to make the most sense.

The idea of the control site being publicly visible is an interesting idea.
I do think it would be possible to add to the domain_group entity access alters that the control site does _not_ get the content at all. It's _probably_ also possible, but more work, to do it such that particular users get to see the content and others don't.

Require Login or similar would have to work with config so that we can enable it on one domain.
Altering the entity access I guess we could just have a checkbox somewhere in the microsites overall configuration?

**Comment by finnlewis** [comment]
Probably wants testing again against Group 3.x

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites/pull/327
