### ISSUE TITLE
[3.x] Update how 'create content' page (and others menu, directory facets)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#298]
Fresh install.
Created one microsite.
Visit : https://localgov-micro.lndo.site/group/1/node/add

```
The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\group\Entity\GroupRelationshipType::getDescription() in Drupal\localgov_microsites_group\EventSubscriber\AlterCreateGroupContentSubscriber->onView() (line 49 of modules/contrib/localgov_microsites_group/src/EventSubscriber/AlterCreateGroupContentSubscriber.php).

Drupal\localgov_microsites_group\EventSubscriber\AlterCreateGroupContentSubscriber->onView(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by ekes** [comment]
/group/1/node/add

Again has a list like:-

Group node (Blog channel)
    Add existing content item of type Blog channel to the group. 

This was being altered, but breaks with 3.x the above commit [c324a5a](https://github.com/localgovdrupal/localgov_microsites_group/commit/c324a5ad1145bd2e5e3550c919247961c761a39f) stops it breaking but doesn't fix the change.

Making the present code work again is possible, though it's not immediately apparent how, now, to pull the 'Blog channel' string from on its own to replace the title, for example.
The text as it stands makes sense for the group content general tab (which as all entity types mixed) but we hide that.
So it might make sense to change these description globally - so that for example:

Group menu (Utility menu)
    Add new group content menu of type Utility menu to the group. 

Also gets fixed at the same time.

So maybe overriding/decorating the service used as a plugin for the UI texts and making them all:-

%bundle_label
  Add %new|existing %bundle_label (%entity_label)

Leaving the %entity_label in the description just for the occasions that an admin does see it mixed up with other entity types?

**Comment by finnlewis** [comment]
For example, the add content page currently looks like this: 

![Image](https://user-images.githubusercontent.com/326588/202493381-bce49a87-3ee8-4494-8a01-a7e372d54deb.png)

We really want this to read like the default add content page: 


![Image](https://user-images.githubusercontent.com/326588/202493594-da640ba0-9f77-4acf-9c5f-979329176277.png)

But also add (content type) to the end of the description to distinguish between other entity types.

**Comment by ekes** [comment]
PR to fix https://github.com/localgovdrupal/localgov_microsites_group/pull/318
